name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AI_NOTEX_PRO }}
          channelId: live
          projectId: ai-notex-pro
          entryPoint: .  # "창고(public) 찾지 말고 여기서 바로 가져가라!"는 특명입니다.
          target: ai-notex-pro
